test_that("unloading leaves no trace", {
  library(mlr3cluster)
  n_learners = length(learners)
  n_learners_total = length(mlr_learners$keys())
  n_measures = length(measures)
  n_measures_total = length(mlr_measures$keys())
  n_tasks = length(tasks)
  n_tasks_total = length(mlr_tasks$keys())

  unloadNamespace("mlr3cluster")
  n_mlr_learners = length(mlr_learners$keys())
  n_mlr_measures = length(mlr_measures$keys())
  n_mlr_tasks = length(mlr_tasks$keys())
  expect_true(n_learners == n_learners_total - n_mlr_learners)
  expect_true(n_measures == n_measures_total - n_mlr_measures)
  expect_true(n_tasks == n_tasks_total - n_mlr_tasks)
})
