# Workflow sets WEKA_HOME and installs XMeans
# r cmd check workflow of the mlr3 ecosystem v0.3.1
# https://github.com/mlr-org/actions
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: r-cmd-check

env:
   WEKA_HOME: /home/runner/work/mlr3cluster

jobs:
  r-cmd-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'devel'}
          - {os: ubuntu-latest,   r: 'release'}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true

      - name: Install XMeans
        run: |
          RWeka::WPM("refresh-cache")
          RWeka::WPM("install-package", "XMeans")
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
